apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: laravel-deplbarca-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: laravel-deplbarca
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 70
